# Generated by Django 4.2.5 on 2023-10-19 09:47

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text="Должно содержать по крайней мере одно слово 'Превосходно' или 'Роскошно'",
                validators=[catalog.models.validate_perfection],
                verbose_name="Текст",
            ),
        ),
    ]
